project_id = "rbfonmpuepqfhivvoqku"

[functions.cron-limpeza-agenda]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.mercado-pago-oauth-start]
verify_jwt = true

[functions.mercado-pago-oauth-callback]
verify_jwt = false

[functions.btg-oauth-start]
verify_jwt = true

[functions.btg-oauth-callback]
verify_jwt = false

[functions.btg-pix-lote]
verify_jwt = false

[functions.btg-webhook]
verify_jwt = false


[functions.btg-repasse-disparar]
verify_jwt = true

[functions.btg-token-refresh]
verify_jwt = false

[functions.btg-pix-webhook]
verify_jwt = false

[functions.btg-cobranca-status]
verify_jwt = true
