/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TermoAdesaoRouteImport } from './routes/termo-adesao'
import { Route as ServicosAdminRouteImport } from './routes/servicos-admin'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfissionalCadastroRouteImport } from './routes/profissional-cadastro'
import { Route as ProfissionalRouteImport } from './routes/profissional'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PorqueRouteImport } from './routes/porque'
import { Route as ParaProfissionaisRouteImport } from './routes/para-profissionais'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as MateriaisAdminRouteImport } from './routes/materiais-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CancelamentoRouteImport } from './routes/cancelamento'
import { Route as ApoioFemininoRouteImport } from './routes/apoio-feminino'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AdminValidacaoRouteImport } from './routes/admin-validacao'
import { Route as AdminRepassesRouteImport } from './routes/admin-repasses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosCategoriaRouteImport } from './routes/servicos.$categoria'
import { Route as MpCallbackRouteImport } from './routes/mp.callback'
import { Route as LoginProfissionalRouteImport } from './routes/login_.profissional'
import { Route as AuthRedirectRouteImport } from './routes/auth.redirect'
import { Route as ProfissionaisPerfilSlugRouteImport } from './routes/profissionais.perfil.$slug'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermoAdesaoRoute = TermoAdesaoRouteImport.update({
  id: '/termo-adesao',
  path: '/termo-adesao',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosAdminRoute = ServicosAdminRouteImport.update({
  id: '/servicos-admin',
  path: '/servicos-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalCadastroRoute = ProfissionalCadastroRouteImport.update({
  id: '/profissional-cadastro',
  path: '/profissional-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalRoute = ProfissionalRouteImport.update({
  id: '/profissional',
  path: '/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PorqueRoute = PorqueRouteImport.update({
  id: '/porque',
  path: '/porque',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaProfissionaisRoute = ParaProfissionaisRouteImport.update({
  id: '/para-profissionais',
  path: '/para-profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisAdminRoute = MateriaisAdminRouteImport.update({
  id: '/materiais-admin',
  path: '/materiais-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelamentoRoute = CancelamentoRouteImport.update({
  id: '/cancelamento',
  path: '/cancelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoioFemininoRoute = ApoioFemininoRouteImport.update({
  id: '/apoio-feminino',
  path: '/apoio-feminino',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminValidacaoRoute = AdminValidacaoRouteImport.update({
  id: '/admin-validacao',
  path: '/admin-validacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRepassesRoute = AdminRepassesRouteImport.update({
  id: '/admin-repasses',
  path: '/admin-repasses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosCategoriaRoute = ServicosCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => ServicosRoute,
} as any)
const MpCallbackRoute = MpCallbackRouteImport.update({
  id: '/mp/callback',
  path: '/mp/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginProfissionalRoute = LoginProfissionalRouteImport.update({
  id: '/login_/profissional',
  path: '/login/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/auth/redirect',
  path: '/auth/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisPerfilSlugRoute = ProfissionaisPerfilSlugRouteImport.update({
  id: '/perfil/$slug',
  path: '/perfil/$slug',
  getParentRoute: () => ProfissionaisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-repasses': typeof AdminRepassesRoute
  '/admin-validacao': typeof AdminValidacaoRoute
  '/ajuda': typeof AjudaRoute
  '/apoio-feminino': typeof ApoioFemininoRoute
  '/cancelamento': typeof CancelamentoRoute
  '/checkout': typeof CheckoutRoute
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/convite': typeof ConviteRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/materiais-admin': typeof MateriaisAdminRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pagamento': typeof PagamentoRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/porque': typeof PorqueRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profissionais': typeof ProfissionaisRouteWithChildren
  '/profissional': typeof ProfissionalRoute
  '/profissional-cadastro': typeof ProfissionalCadastroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/servicos-admin': typeof ServicosAdminRoute
  '/termo-adesao': typeof TermoAdesaoRoute
  '/termos': typeof TermosRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/login/profissional': typeof LoginProfissionalRoute
  '/mp/callback': typeof MpCallbackRoute
  '/servicos/$categoria': typeof ServicosCategoriaRoute
  '/profissionais/perfil/$slug': typeof ProfissionaisPerfilSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-repasses': typeof AdminRepassesRoute
  '/admin-validacao': typeof AdminValidacaoRoute
  '/ajuda': typeof AjudaRoute
  '/apoio-feminino': typeof ApoioFemininoRoute
  '/cancelamento': typeof CancelamentoRoute
  '/checkout': typeof CheckoutRoute
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/convite': typeof ConviteRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/materiais-admin': typeof MateriaisAdminRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pagamento': typeof PagamentoRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/porque': typeof PorqueRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profissionais': typeof ProfissionaisRouteWithChildren
  '/profissional': typeof ProfissionalRoute
  '/profissional-cadastro': typeof ProfissionalCadastroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/servicos-admin': typeof ServicosAdminRoute
  '/termo-adesao': typeof TermoAdesaoRoute
  '/termos': typeof TermosRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/login/profissional': typeof LoginProfissionalRoute
  '/mp/callback': typeof MpCallbackRoute
  '/servicos/$categoria': typeof ServicosCategoriaRoute
  '/profissionais/perfil/$slug': typeof ProfissionaisPerfilSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-repasses': typeof AdminRepassesRoute
  '/admin-validacao': typeof AdminValidacaoRoute
  '/ajuda': typeof AjudaRoute
  '/apoio-feminino': typeof ApoioFemininoRoute
  '/cancelamento': typeof CancelamentoRoute
  '/checkout': typeof CheckoutRoute
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/convite': typeof ConviteRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/materiais-admin': typeof MateriaisAdminRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pagamento': typeof PagamentoRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/porque': typeof PorqueRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profissionais': typeof ProfissionaisRouteWithChildren
  '/profissional': typeof ProfissionalRoute
  '/profissional-cadastro': typeof ProfissionalCadastroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/servicos-admin': typeof ServicosAdminRoute
  '/termo-adesao': typeof TermoAdesaoRoute
  '/termos': typeof TermosRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/login_/profissional': typeof LoginProfissionalRoute
  '/mp/callback': typeof MpCallbackRoute
  '/servicos/$categoria': typeof ServicosCategoriaRoute
  '/profissionais/perfil/$slug': typeof ProfissionaisPerfilSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-repasses'
    | '/admin-validacao'
    | '/ajuda'
    | '/apoio-feminino'
    | '/cancelamento'
    | '/checkout'
    | '/cliente'
    | '/contato'
    | '/convite'
    | '/equipe'
    | '/login'
    | '/materiais-admin'
    | '/orcamentos'
    | '/pagamento'
    | '/para-profissionais'
    | '/porque'
    | '/privacidade'
    | '/profissionais'
    | '/profissional'
    | '/profissional-cadastro'
    | '/reset-password'
    | '/servicos'
    | '/servicos-admin'
    | '/termo-adesao'
    | '/termos'
    | '/auth/redirect'
    | '/login/profissional'
    | '/mp/callback'
    | '/servicos/$categoria'
    | '/profissionais/perfil/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-repasses'
    | '/admin-validacao'
    | '/ajuda'
    | '/apoio-feminino'
    | '/cancelamento'
    | '/checkout'
    | '/cliente'
    | '/contato'
    | '/convite'
    | '/equipe'
    | '/login'
    | '/materiais-admin'
    | '/orcamentos'
    | '/pagamento'
    | '/para-profissionais'
    | '/porque'
    | '/privacidade'
    | '/profissionais'
    | '/profissional'
    | '/profissional-cadastro'
    | '/reset-password'
    | '/servicos'
    | '/servicos-admin'
    | '/termo-adesao'
    | '/termos'
    | '/auth/redirect'
    | '/login/profissional'
    | '/mp/callback'
    | '/servicos/$categoria'
    | '/profissionais/perfil/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-repasses'
    | '/admin-validacao'
    | '/ajuda'
    | '/apoio-feminino'
    | '/cancelamento'
    | '/checkout'
    | '/cliente'
    | '/contato'
    | '/convite'
    | '/equipe'
    | '/login'
    | '/materiais-admin'
    | '/orcamentos'
    | '/pagamento'
    | '/para-profissionais'
    | '/porque'
    | '/privacidade'
    | '/profissionais'
    | '/profissional'
    | '/profissional-cadastro'
    | '/reset-password'
    | '/servicos'
    | '/servicos-admin'
    | '/termo-adesao'
    | '/termos'
    | '/auth/redirect'
    | '/login_/profissional'
    | '/mp/callback'
    | '/servicos/$categoria'
    | '/profissionais/perfil/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminRepassesRoute: typeof AdminRepassesRoute
  AdminValidacaoRoute: typeof AdminValidacaoRoute
  AjudaRoute: typeof AjudaRoute
  ApoioFemininoRoute: typeof ApoioFemininoRoute
  CancelamentoRoute: typeof CancelamentoRoute
  CheckoutRoute: typeof CheckoutRoute
  ClienteRoute: typeof ClienteRoute
  ContatoRoute: typeof ContatoRoute
  ConviteRoute: typeof ConviteRoute
  EquipeRoute: typeof EquipeRoute
  LoginRoute: typeof LoginRoute
  MateriaisAdminRoute: typeof MateriaisAdminRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PagamentoRoute: typeof PagamentoRoute
  ParaProfissionaisRoute: typeof ParaProfissionaisRoute
  PorqueRoute: typeof PorqueRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProfissionaisRoute: typeof ProfissionaisRouteWithChildren
  ProfissionalRoute: typeof ProfissionalRoute
  ProfissionalCadastroRoute: typeof ProfissionalCadastroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  ServicosAdminRoute: typeof ServicosAdminRoute
  TermoAdesaoRoute: typeof TermoAdesaoRoute
  TermosRoute: typeof TermosRoute
  AuthRedirectRoute: typeof AuthRedirectRoute
  LoginProfissionalRoute: typeof LoginProfissionalRoute
  MpCallbackRoute: typeof MpCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termo-adesao': {
      id: '/termo-adesao'
      path: '/termo-adesao'
      fullPath: '/termo-adesao'
      preLoaderRoute: typeof TermoAdesaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos-admin': {
      id: '/servicos-admin'
      path: '/servicos-admin'
      fullPath: '/servicos-admin'
      preLoaderRoute: typeof ServicosAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional-cadastro': {
      id: '/profissional-cadastro'
      path: '/profissional-cadastro'
      fullPath: '/profissional-cadastro'
      preLoaderRoute: typeof ProfissionalCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional': {
      id: '/profissional'
      path: '/profissional'
      fullPath: '/profissional'
      preLoaderRoute: typeof ProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porque': {
      id: '/porque'
      path: '/porque'
      fullPath: '/porque'
      preLoaderRoute: typeof PorqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-profissionais': {
      id: '/para-profissionais'
      path: '/para-profissionais'
      fullPath: '/para-profissionais'
      preLoaderRoute: typeof ParaProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais-admin': {
      id: '/materiais-admin'
      path: '/materiais-admin'
      fullPath: '/materiais-admin'
      preLoaderRoute: typeof MateriaisAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancelamento': {
      id: '/cancelamento'
      path: '/cancelamento'
      fullPath: '/cancelamento'
      preLoaderRoute: typeof CancelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoio-feminino': {
      id: '/apoio-feminino'
      path: '/apoio-feminino'
      fullPath: '/apoio-feminino'
      preLoaderRoute: typeof ApoioFemininoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-validacao': {
      id: '/admin-validacao'
      path: '/admin-validacao'
      fullPath: '/admin-validacao'
      preLoaderRoute: typeof AdminValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-repasses': {
      id: '/admin-repasses'
      path: '/admin-repasses'
      fullPath: '/admin-repasses'
      preLoaderRoute: typeof AdminRepassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$categoria': {
      id: '/servicos/$categoria'
      path: '/$categoria'
      fullPath: '/servicos/$categoria'
      preLoaderRoute: typeof ServicosCategoriaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/mp/callback': {
      id: '/mp/callback'
      path: '/mp/callback'
      fullPath: '/mp/callback'
      preLoaderRoute: typeof MpCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/profissional': {
      id: '/login_/profissional'
      path: '/login/profissional'
      fullPath: '/login/profissional'
      preLoaderRoute: typeof LoginProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/redirect': {
      id: '/auth/redirect'
      path: '/auth/redirect'
      fullPath: '/auth/redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais/perfil/$slug': {
      id: '/profissionais/perfil/$slug'
      path: '/perfil/$slug'
      fullPath: '/profissionais/perfil/$slug'
      preLoaderRoute: typeof ProfissionaisPerfilSlugRouteImport
      parentRoute: typeof ProfissionaisRoute
    }
  }
}

interface ProfissionaisRouteChildren {
  ProfissionaisPerfilSlugRoute: typeof ProfissionaisPerfilSlugRoute
}

const ProfissionaisRouteChildren: ProfissionaisRouteChildren = {
  ProfissionaisPerfilSlugRoute: ProfissionaisPerfilSlugRoute,
}

const ProfissionaisRouteWithChildren = ProfissionaisRoute._addFileChildren(
  ProfissionaisRouteChildren,
)

interface ServicosRouteChildren {
  ServicosCategoriaRoute: typeof ServicosCategoriaRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosCategoriaRoute: ServicosCategoriaRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminRepassesRoute: AdminRepassesRoute,
  AdminValidacaoRoute: AdminValidacaoRoute,
  AjudaRoute: AjudaRoute,
  ApoioFemininoRoute: ApoioFemininoRoute,
  CancelamentoRoute: CancelamentoRoute,
  CheckoutRoute: CheckoutRoute,
  ClienteRoute: ClienteRoute,
  ContatoRoute: ContatoRoute,
  ConviteRoute: ConviteRoute,
  EquipeRoute: EquipeRoute,
  LoginRoute: LoginRoute,
  MateriaisAdminRoute: MateriaisAdminRoute,
  OrcamentosRoute: OrcamentosRoute,
  PagamentoRoute: PagamentoRoute,
  ParaProfissionaisRoute: ParaProfissionaisRoute,
  PorqueRoute: PorqueRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProfissionaisRoute: ProfissionaisRouteWithChildren,
  ProfissionalRoute: ProfissionalRoute,
  ProfissionalCadastroRoute: ProfissionalCadastroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicosRoute: ServicosRouteWithChildren,
  ServicosAdminRoute: ServicosAdminRoute,
  TermoAdesaoRoute: TermoAdesaoRoute,
  TermosRoute: TermosRoute,
  AuthRedirectRoute: AuthRedirectRoute,
  LoginProfissionalRoute: LoginProfissionalRoute,
  MpCallbackRoute: MpCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
