/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosAdminRouteImport } from './routes/servicos-admin'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfissionalRouteImport } from './routes/profissional'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as PorqueRouteImport } from './routes/porque'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as MateriaisAdminRouteImport } from './routes/materiais-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosCategoriaRouteImport } from './routes/servicos.$categoria'
import { Route as LoginProfissionalRouteImport } from './routes/login.profissional'
import { Route as ProfissionaisPerfilSlugRouteImport } from './routes/profissionais.perfil.$slug'

const ServicosAdminRoute = ServicosAdminRouteImport.update({
  id: '/servicos-admin',
  path: '/servicos-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalRoute = ProfissionalRouteImport.update({
  id: '/profissional',
  path: '/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const PorqueRoute = PorqueRouteImport.update({
  id: '/porque',
  path: '/porque',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisAdminRoute = MateriaisAdminRouteImport.update({
  id: '/materiais-admin',
  path: '/materiais-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosCategoriaRoute = ServicosCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => ServicosRoute,
} as any)
const LoginProfissionalRoute = LoginProfissionalRouteImport.update({
  id: '/profissional',
  path: '/profissional',
  getParentRoute: () => LoginRoute,
} as any)
const ProfissionaisPerfilSlugRoute = ProfissionaisPerfilSlugRouteImport.update({
  id: '/perfil/$slug',
  path: '/perfil/$slug',
  getParentRoute: () => ProfissionaisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/checkout': typeof CheckoutRoute
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRouteWithChildren
  '/materiais-admin': typeof MateriaisAdminRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pagamento': typeof PagamentoRoute
  '/porque': typeof PorqueRoute
  '/profissionais': typeof ProfissionaisRouteWithChildren
  '/profissional': typeof ProfissionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/servicos-admin': typeof ServicosAdminRoute
  '/login/profissional': typeof LoginProfissionalRoute
  '/servicos/$categoria': typeof ServicosCategoriaRoute
  '/profissionais/perfil/$slug': typeof ProfissionaisPerfilSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/checkout': typeof CheckoutRoute
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRouteWithChildren
  '/materiais-admin': typeof MateriaisAdminRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pagamento': typeof PagamentoRoute
  '/porque': typeof PorqueRoute
  '/profissionais': typeof ProfissionaisRouteWithChildren
  '/profissional': typeof ProfissionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/servicos-admin': typeof ServicosAdminRoute
  '/login/profissional': typeof LoginProfissionalRoute
  '/servicos/$categoria': typeof ServicosCategoriaRoute
  '/profissionais/perfil/$slug': typeof ProfissionaisPerfilSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/checkout': typeof CheckoutRoute
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRouteWithChildren
  '/materiais-admin': typeof MateriaisAdminRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pagamento': typeof PagamentoRoute
  '/porque': typeof PorqueRoute
  '/profissionais': typeof ProfissionaisRouteWithChildren
  '/profissional': typeof ProfissionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/servicos-admin': typeof ServicosAdminRoute
  '/login/profissional': typeof LoginProfissionalRoute
  '/servicos/$categoria': typeof ServicosCategoriaRoute
  '/profissionais/perfil/$slug': typeof ProfissionaisPerfilSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/checkout'
    | '/cliente'
    | '/contato'
    | '/login'
    | '/materiais-admin'
    | '/orcamentos'
    | '/pagamento'
    | '/porque'
    | '/profissionais'
    | '/profissional'
    | '/reset-password'
    | '/servicos'
    | '/servicos-admin'
    | '/login/profissional'
    | '/servicos/$categoria'
    | '/profissionais/perfil/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/checkout'
    | '/cliente'
    | '/contato'
    | '/login'
    | '/materiais-admin'
    | '/orcamentos'
    | '/pagamento'
    | '/porque'
    | '/profissionais'
    | '/profissional'
    | '/reset-password'
    | '/servicos'
    | '/servicos-admin'
    | '/login/profissional'
    | '/servicos/$categoria'
    | '/profissionais/perfil/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuda'
    | '/checkout'
    | '/cliente'
    | '/contato'
    | '/login'
    | '/materiais-admin'
    | '/orcamentos'
    | '/pagamento'
    | '/porque'
    | '/profissionais'
    | '/profissional'
    | '/reset-password'
    | '/servicos'
    | '/servicos-admin'
    | '/login/profissional'
    | '/servicos/$categoria'
    | '/profissionais/perfil/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AjudaRoute: typeof AjudaRoute
  CheckoutRoute: typeof CheckoutRoute
  ClienteRoute: typeof ClienteRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRouteWithChildren
  MateriaisAdminRoute: typeof MateriaisAdminRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PagamentoRoute: typeof PagamentoRoute
  PorqueRoute: typeof PorqueRoute
  ProfissionaisRoute: typeof ProfissionaisRouteWithChildren
  ProfissionalRoute: typeof ProfissionalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  ServicosAdminRoute: typeof ServicosAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos-admin': {
      id: '/servicos-admin'
      path: '/servicos-admin'
      fullPath: '/servicos-admin'
      preLoaderRoute: typeof ServicosAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional': {
      id: '/profissional'
      path: '/profissional'
      fullPath: '/profissional'
      preLoaderRoute: typeof ProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porque': {
      id: '/porque'
      path: '/porque'
      fullPath: '/porque'
      preLoaderRoute: typeof PorqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais-admin': {
      id: '/materiais-admin'
      path: '/materiais-admin'
      fullPath: '/materiais-admin'
      preLoaderRoute: typeof MateriaisAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$categoria': {
      id: '/servicos/$categoria'
      path: '/$categoria'
      fullPath: '/servicos/$categoria'
      preLoaderRoute: typeof ServicosCategoriaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/login/profissional': {
      id: '/login/profissional'
      path: '/profissional'
      fullPath: '/login/profissional'
      preLoaderRoute: typeof LoginProfissionalRouteImport
      parentRoute: typeof LoginRoute
    }
    '/profissionais/perfil/$slug': {
      id: '/profissionais/perfil/$slug'
      path: '/perfil/$slug'
      fullPath: '/profissionais/perfil/$slug'
      preLoaderRoute: typeof ProfissionaisPerfilSlugRouteImport
      parentRoute: typeof ProfissionaisRoute
    }
  }
}

interface LoginRouteChildren {
  LoginProfissionalRoute: typeof LoginProfissionalRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginProfissionalRoute: LoginProfissionalRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface ProfissionaisRouteChildren {
  ProfissionaisPerfilSlugRoute: typeof ProfissionaisPerfilSlugRoute
}

const ProfissionaisRouteChildren: ProfissionaisRouteChildren = {
  ProfissionaisPerfilSlugRoute: ProfissionaisPerfilSlugRoute,
}

const ProfissionaisRouteWithChildren = ProfissionaisRoute._addFileChildren(
  ProfissionaisRouteChildren,
)

interface ServicosRouteChildren {
  ServicosCategoriaRoute: typeof ServicosCategoriaRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosCategoriaRoute: ServicosCategoriaRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AjudaRoute: AjudaRoute,
  CheckoutRoute: CheckoutRoute,
  ClienteRoute: ClienteRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRouteWithChildren,
  MateriaisAdminRoute: MateriaisAdminRoute,
  OrcamentosRoute: OrcamentosRoute,
  PagamentoRoute: PagamentoRoute,
  PorqueRoute: PorqueRoute,
  ProfissionaisRoute: ProfissionaisRouteWithChildren,
  ProfissionalRoute: ProfissionalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicosRoute: ServicosRouteWithChildren,
  ServicosAdminRoute: ServicosAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
